<?php
/**
 * Created by PhpStorm.
 * User: Michu
 * Date: 8/23/2017
 * Time: 8:16 AM
 */
namespace App\Controller;
use App\Controller\AppController;
use Cake\Event\Event;

class RemoteIPsController extends AppController {
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        pr($this->getRealIpAddr());
        $this->autoRender = false;

    }

    public function getRealIpAddr()
    {
        if (!empty($_SERVER['HTTP_CLIENT_IP']))   //check ip from share internet
        {
            $ip=$_SERVER['HTTP_CLIENT_IP'];
        }
        elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))   //to check ip is pass from proxy
        {
            $ip=$_SERVER['HTTP_X_FORWARDED_FOR'];
        }
        else
        {
            $ip=$_SERVER['REMOTE_ADDR'];
        }
        return $ip;
    }
}